device:
    gpu: 5
    n_workers: 16

model:
    arch: bisenetX39
    version: cityscapes
    path: /path/to/pretrained/bisenet/bisenetX39_cityscapes.pth
    with_bn: True

data:
    dataset: cityscapes
    version: ddrnet_23 #needed for pretrained version
    train_split: val
    val_split: val
    test_split: test
    img_rows: 1024
    img_cols: 2048
    path: /path/to/cityscapes/root
    img_norm: True
    bottom_crop: 0 
    bgr: False
    std_version: ddrnet_23

adv_patch:
    path: 
        resume: #./exp/22_april_2021/patches/patch_final_11.png # FOR RESUMING OPTIMIZATION
        out_dir: ./exp/
        save_patch: True
        exp_name: exp_name
        save_image_log: 1
        
    optimization:
        optimizer:
            lr: 0.5
            name: adam
        loss:
            adv_loss:
                name: 'multi_scale_patch_composition_targeted'
                args: 0.0
                mult_factor: 1.0
            smoothness:
                name: 'smoothness_loss'
                args: None
                mult_factor: 0.0
            NPS:
                name: 'NPS'
                args: '/path/to/printable/color/list/printable_colors_test.txt'
                mult_factor: 0.0


        num_opt_samples: 100
        opt_iters: 200
        batch_size: 10

        use_multiple_outputs: False    # Aux logits on/off

        batch_size_val: 15
        test_log: 50 # test_every
        checkpoint_patch: 50   # save_every

        opt_validation_log1: True   # online_validation

        # EOT
        use_transformations: True
    

    attr:
        width : 600
        height : 300
        pos_x:
        pos_y:
